@baseUrl = http://localhost:3000/api/v1/

### Player

# @name PlayerGetAll
GET {{baseUrl}}player
?limit=10
&offset=0

###
# @name PlayerGetOne
GET {{baseUrl}}player/69a1a9189fda1c56f912a828d

###
# @name PlayerPost
POST {{baseUrl}}player
Content-Type: application/json

{
  "name": "Test2",
  "email": "test@gmail.com",
  "tell": "949734857234",
  "ranking": "A",
  "positionRanking": 1,
  "pictureUrl": "http://localhost:3000/picture/3"
}

###
# @name PlayerPatch
PATCH  {{baseUrl}}player/69a45f627629b7556f0d5ed6
Content-Type: application/json

{
  "name": "test updated"
}
###
# @name PlayerDelete
DELETE  {{baseUrl}}player/69a1b7ebe38a2c3bfabd7999



### Category

# @name CategoryGetAll
GET {{baseUrl}}category
?limit=10
&offset=0

###
# @name CategoryGetOne
GET {{baseUrl}}category/69a45d44f8f5fdc6cefa39db

###
# @name CategoryPost
POST {{baseUrl}}category
Content-Type: application/json

{
  "name": "Category Test",
  "description": "Medium category",
  "events": [
    {
      "name": "Event one",
      "operation": "any operation",
      "value": 50
    },
    {
      "name": "Event two",
      "operation": "any operation",
      "value": 25
    }
  ]

}

###
# @name CategoryPatch
PATCH  {{baseUrl}}category/69a49b34c1b95f623aeb8a5f
Content-Type: application/json

{
  "name": "Category update name",
  "addPlayers": ["69a1a8f29fda1c56f912a825", "69a45d44f8f5fdc6cefa39db"],
  "removePlayers": ["69a45f627629b7556f0d5ed6"],
  "addEvents": [
    {
      "name": "Event four",
      "operation": "any operation",
      "value": 100
    }
  ],
  "removeEvents": [
    {
      "name": "Event two"
    }
  ]
}
###
# @name CategoryDelete
DELETE  {{baseUrl}}category/69a45d44f8f5fdc6cefa39db
